DEFAULT_LANGUAGE = 'en'
DEFAULT_LOG_LEVEL = 'WARNING'
DEFAULT_DB_URL = 'sqlite:///hotspot.db'
DEFAULT_REDIS_URL = 'unix:///tmp/redis.sock?db=0'
DEFAULT_ONLINE_TIMEOUT = 300
DEFAULT_AUTH_PORT = 1812
DEFAULT_ACCT_PORT = 1813
DEFAULT_COA_PORT = 3799
