# Workflow Gitea Actions
name: Docker Build

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*' ]
  workflow_dispatch:
    inputs:
      registry:
        description: 'Docker registry to push the built image'
        required: true
        default: 'registry.service.sova'
      image_name:
        description: 'Name of the Docker image to build and push'
        required: true
        default: 'sova/hotspot-mikrotik'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        db-backend: ['sqlite', 'postgres', 'mysql']
    env:
      REGISTRY: ${{ inputs.registry }}
      IMAGE_NAME: ${{ inputs.image_name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        tags: true

    - name: Get latest tag
      id: get_version
      run: echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

    - name: Set LATEST_TAG variable
      id: set_latest_tag
      run: |
        if [[ "${{ env.VERSION }}" =~ (beta|alpha|rc) ]]; then
          echo "LATEST_TAG=" >> $GITHUB_ENV
        else
          echo "LATEST_TAG=latest" >> $GITHUB_ENV
        fi

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.SOVA_REGISTRY_USER }}
        password: ${{ secrets.SOVA_REGISTRY_PASS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        build-args: |
          DB_BACKEND=${{ matrix.db-backend }}
        labels: |
          VERSION=${{ env.VERSION }}
          DB_BACKEND=${{ matrix.db-backend }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}-${{ matrix.db-backend }}${{ matrix.db-backend == 'sqlite' && env.LATEST_TAG && format(',{0}/{1}:latest', env.REGISTRY, env.IMAGE_NAME) || '' }}
