name: Tests

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:    # ручной запуск из Actions UI
  
jobs:
  test:
    runs-on: alpine-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Test auth with pytest
      run: |
        pytest tests/test_auth.py
    
    - name: Test admin with pytest
      run: |
        pytest tests/test_admin.py
