users:
  guest:
    password: secret
    delay: 24h # Days. You can use suffixes such as: w, d, m, s. Without a suffix, the default is hours.
  employee:
    password: supersecret
    delay: 30d # Days. You can use suffixes such as: w, d, m, s. Without a suffix, the default is hours.
