settings:
  company_name: No-name LTD
  language: en-US
  sender:
    type: smsru
    api_key: YOUR-API-KEY  # Setup your api key
  hotspot_users:
    guest:
      password: secret
      delay: 24h # Hours. You can use suffixes such as: w, d, m, s. Without a suffix, the default is hours.
    employee:
      password: supersecret
      delay: 30d # Days. You can use suffixes such as: w, d, m, s. Without a suffix, the default is hours.
